baseURL = 'https://stac.club/'
title        = "The Science And Technology Club"
languageCode = "en-us"
theme        = "hugo-theme-hello-friend-ng-master"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "STACC breaks down barriers for students who would like to be invlolved in the tech industry. We provide guidance through experienced professors and students, along with events that showcase important skills."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Enable dark/light toggle
  enableThemeToggle = true

  # Metadata mostly used in document's head
  description = "The official website for STACC at RELLIS"
  keywords = "homepage, blog"
  images = [""]

  [[params.social]]
    name = "instagram"
    url  = "https://instagram.com/staccxrellis"

[params.logo]
    logoMark     = ">"
    logoText     = "$ cd STACC/"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#07a500"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    logoCursorAnimate  = "1s"

[params.footer]
    trademark = true
    rss = false
    copyright = false
    author = true

    topText = []
    bottomText = [
      "The Science Technology And Computing Club",
      "TAMUC at RELLIS"
    ]

# [params.portrait]
#    path     = "/images/OFFICIAL_green_logo.PNG"
#    alt      = "Logo"
#    maxWidth = "500px"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "The Science Technology And Computing Club"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  # And you can even create generic menu
  [main]
    [[menu.main]]
      identifier = "join"
      name       = "Join STACC"
      url        = "/join"
    [[menu.main]]
      identifier = "about"
      name       = "About"
      url        = "about/"
    [[menu.main]]
      identifier = "ctf"
      name       = "CTF"
      url        = "ctf/"

# Allows for html tag rendering in markdown files
[markup.goldmark.renderer]
  unsafe = true
