baseURL = 'https://stac.club/'
title        = "Science Technology And Computing Club"
languageCode = "en-us"
theme        = "hugo-theme-hello-friend-ng-master"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "The Science Technology and Computing Club (STACC) will indiscriminately provide a resource for student members within the TAMU System RELLIS Campus to develop social interaction confidence, basic through advanced computer knowledge and information technology expertise."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Enable dark/light toggle
  enableThemeToggle = true

  # Metadata mostly used in document's head
  description = "The official website for STACC at RELLIS"
  keywords = "homepage, blog"
  images = [""]

  [[params.social]]
    name = "instagram"
    url  = "https://instagram.com/staccxrellis"
  [[params.social]]
    name = "discord"
    url  = "https://discord.gg/uzxc543peQ"

[params.logo]
    logoMark     = ">"
    logoText     = "$ cd STACC/"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#07a500"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    logoCursorAnimate  = "1s"

[params.footer]
    trademark = true
    rss = false
    copyright = false
    author = false

    topText = ["Science Technology And Computing Club"]
    bottomText = ["TAMUC at RELLIS"]

# [params.portrait]
#    path     = "/images/OFFICIAL_green_logo.PNG"
#    alt      = "Logo"
#    maxWidth = "500px"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Science Technology And Computing Club"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  # And you can even create generic menu
  [main]
    [[menu.main]]
      identifier = "about"
      name       = "About"
      url        = "about/"
    [[menu.main]]
      identifier = "Support Us"
      name       = "Support Us"
      url        = "support/"

# Allows for html tag rendering in markdown files
[markup.goldmark.renderer]
  unsafe = true
